const jwt = require('jsonwebtoken');
const config = require('../../config');
const { ApiError } = require('../../utils');

const { User } = require('../../models');

/**
 * Middleware to verify JWT token generated by SIWE
 */
const requireAuth = async (req, res, next) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw ApiError.unauthorized('Authentication token is missing or invalid');
    }

    const token = authHeader.split(' ')[1];
    
    // Verify the JWT token
    const decoded = jwt.verify(token, config.jwtSecret);
    const addrLower = (decoded.address || '').toLowerCase();
    
    const isSuperAdminAddr = ['0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266', '0x21d797924c7f53a479b1836154bb3f721d01330b', '0xb588d99161cae188d279dcedc94c934e2b2a3f4d'].includes(addrLower);
    const isAdminAddr = ['0x70997970c51812dc3a010c7d01b50e0d17dc79c8', '0xdf6e18a4e9b33fd762fb4d7f69a40528198cd381'].includes(addrLower);

    let currentRole = decoded.role;
    if (isSuperAdminAddr) {
      currentRole = 'superadmin';
    } else if (isAdminAddr) {
      currentRole = 'admin';
    } else {
      try {
        const dbUser = await User.findOne({ walletAddress: addrLower }).select('role').lean();
        if (dbUser && dbUser.role) {
          currentRole = dbUser.role;
        }
      } catch (e) {
        // Fallback to token role if DB query fails
      }
    }
    
    // Attach user info to request object
    req.user = {
      userId: decoded.userId,
      address: decoded.address,
      role: currentRole,
      chainId: decoded.chainId
    };

    next();
  } catch (error) {
    if (error.name === 'TokenExpiredError') {
      return next(ApiError.unauthorized('Session has expired. Please sign in again.'));
    }
    return next(ApiError.unauthorized('Invalid authentication token'));
  }
};

module.exports = {
  requireAuth
};
